// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBsPIumSTKyITt4mUwexqgqbtHHpnUMJo',
    appId: '1:58944183765:web:c84d59cbb324d71b44b15c',
    messagingSenderId: '58944183765',
    projectId: 'ecommerceapp-1f5a6',
    authDomain: 'ecommerceapp-1f5a6.firebaseapp.com',
    storageBucket: 'ecommerceapp-1f5a6.appspot.com',
    measurementId: 'G-4VYQ3C379M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdDcomxvrhei4uPZVfCQoStPG9RiEc4BQ',
    appId: '1:58944183765:android:863f0b266a424b5944b15c',
    messagingSenderId: '58944183765',
    projectId: 'ecommerceapp-1f5a6',
    storageBucket: 'ecommerceapp-1f5a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYtvI3DHR2C7or8eR_LOGOV1OOtJ6lFqM',
    appId: '1:58944183765:ios:02f52f24eb9d304b44b15c',
    messagingSenderId: '58944183765',
    projectId: 'ecommerceapp-1f5a6',
    storageBucket: 'ecommerceapp-1f5a6.appspot.com',
    androidClientId: '58944183765-0o715q7e01mvk5bugcgfednmq9spdl3s.apps.googleusercontent.com',
    iosClientId: '58944183765-5spjqgla8s9rv0rfj44b3hehv1e2pg40.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
